config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: [:create, :new] #/gardens/:garden_id
  end
  resources :plants, only: :destroy do
    resources :plant_tags, only: [:new, :create]
  end

  resources :plant_tags, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags
  has_many :tags, through: :plant_tags
  validates :name, presence: true
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant # @plant_tag.plant
  belongs_to :tag
  validates :plant_id, uniqueness: {scope: :tag_id}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController

  def new
    @plant_tag = PlantTag.new
    @plant = Plant.find(params[:plant_id])
  end

  def create
    @plant = Plant.find(params[:plant_id])
    params[:plant_tag][:tag].each do |tag|
      PlantTag.create(tag: Tag.find(tag.to_i), plant: @plant)
    end
    redirect_to garden_path(@plant.garden)
  end

  def destroy
    @plant_tag = PlantTag.find(params[:id])
    @garden = @plant_tag.plant.garden
    @plant_tag.destroy
    redirect_to garden_path(@garden)
  end

  private

  def plant_tag_params
    params.require(:plant_tag).permit(:tag_id)
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def new
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params) # name image_url
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden # @plant.garden_id = @garden.id
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @garden = @plant.garden
    @plant.destroy
    redirect_to garden_path(@garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="container">
  <% @garden.plants.each do |plant| %>
    <div class="card-category mt-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= plant.image_url%>')">
      <%= plant.name %>
      <div class="card-tags">
        <% plant.plant_tags.each do |plant_tag| %>
          <span><%= plant_tag.tag.name %></span>
          <%= link_to "Remove tag", plant_tag_path(plant_tag), method: :delete, data: {confirm: "sure?"} %>
        <% end %>
        <%= link_to "+", new_plant_plant_tag_path(plant) %>
      </div>
    </div>
    <%= link_to "destroy plant", plant_path(plant), method: :delete, data: {confirm: "Are you sure?"}, class:'btn btn-danger mt-2' %>
  <% end %>
  <%# button to create new plant %>
  <div class="mt-4">
    <%= link_to "create new plant", new_garden_plant_path(@garden), class:'btn btn-secondary' %>

    <%= link_to 'Edit', edit_garden_path(@garden), class:'btn btn-warning' %>
    <%= link_to 'Back', gardens_path, class:'btn btn-ghost' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenAndPlants700</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container">
  <%= simple_form_for [@plant, @plant_tag] do |f| %>
  <%= f.input :tag, collection: Tag.all, input_html: { multiple: true, class:"multiple-select" }, include_hidden: false %>
  <%= f.submit %>
  <% end %>
</div>

app/views/plants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= simple_form_for [@garden, @plant] do |f| %>
      <%= f.input :name %>
      <%= f.input :image_url %>
      <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>